fixed_frame: "nav"
base_frame: "pelican"
use_imu: false
use_odom: false
use_tf: true
publish_tf: false
publish_marker: true
publish_pose: false
publish_dpose: true
init_pose2d: false
use_cloud_input: true
do_compute_covariance: 1
max_linear_correction: 0.1
max_angular_correction_deg: 10
max_correspondence_dist: 0.2