sizes: "5 3 10 240 3 6 3"
topics: "scan_margin_right1 scan_down scan_margin_right2 scan_front scan_margin_left1 scan_up scan_margin_left2"
frames: "/laser_down /laser_down /laser_down /laser /laser_up /laser_up /laser_up"
